[auth.users.admin]
nome = "Administrador"
senha_hash = "COLOQUE_AQUI_O_HASH_REAL_DA_SENHA_DO_ADMIN"
perfil = "admin"

[auth.users.clebio]
nome = "Clébio Barbosa"
senha_hash = "COLOQUE_AQUI_O_HASH_REAL_DA_SENHA_DO_CLEBIO"
perfil = "admin"
